# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b69cc0a2aa9191da0c15a1f1e6dc994e75b98067061ffd77726e3b55b4ce90a523ba2d49ed2b577c204d4186b6764a94c748778148a9f1e171d90ab59ea7275c

test:
  secret_key_base: f932e745ff97c1127a65f36998975068f4ac8c3d766446a6df69ae200b419b8093c22ca3c7013047bc59c1cbaeade7d9ce66cbd838d208d75542b84fbf16e224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
